/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('img/assets/messingaround.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials.Material} position={[0, 0, 0]} rotation={[0.46, 0.54, -0.72]}>
        <mesh geometry={nodes.Beaker.geometry} material={materials['Material.002']} position={[0.42, 0.075, 0.81]} rotation={[-1.57, 0, 0.81]} scale={[0.57, 0.57, 0.01]} />
        <mesh geometry={nodes.CO.geometry} material={materials['Material.002']} position={[-0.86, -0.47, 1.03]} rotation={[Math.PI / 2, 0, 0]} scale={[1, 1, 1.43]} />
        <mesh geometry={nodes.LABS.geometry} material={materials['Material.002']} position={[1, 0.2, 0.76]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[1, 1, 0.93]} />
        <mesh geometry={nodes.NFT.geometry} material={materials['Material.002']} position={[-0.25, -0.21, -1.03]} rotation={[Math.PI / 2, -Math.PI / 4, Math.PI]} scale={0.96} />
        <mesh geometry={nodes.Outline.geometry} material={materials['Material.002']} scale={0.99} />
        <mesh geometry={nodes.Smiley_Eyes.geometry} material={materials['Material.002']} position={[-0.42, 1, 0.33]} rotation={[0, 0.73, 0.01]} scale={0.8} />
        <mesh geometry={nodes.Smiley_Head.geometry} material={materials['Material.002']} position={[-0.01, 1, 0]} scale={0.92} />
        <mesh geometry={nodes.Smiley_Smile.geometry} material={materials['Material.002']} position={[0.72, 1, 0.31]} rotation={[-Math.PI, 0.81, -Math.PI]} scale={1.43} />
        <mesh geometry={nodes.WEB3.geometry} material={materials['Material.002']} position={[-1.02, -0.24, -0.23]} rotation={[2.36, 0, Math.PI / 2]} scale={0.81} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/messingaround.gltf')
